### PR TITLE
Are any of these commit useful to you?

### PR DESCRIPTION
**Pull request by otherjon**
I made a few changes to swervepy for our team.  I think they might be generally useful.  Happy to make additional changes to make things more compatible with the direction you want to go.

I've added an AbsoluteDutyCycleEncoder class, since our team is currently using SRX Mag Encoders which plug directly into the RoboRIO.  Anyone else doing something similar can use this class.

I fixed a place where the use of 4 swerve modules was hard-coded, since the design seems to indicate a goal of flexibility on the number of swerve modules.

However, the big item is that I refactored the example robot.  The first thing I wanted to do when I downloaded swervepy was to try to demonstrate successful operation on our robot.  Instead of reading and understanding the implementation, I found it easier to have a `constants.py` file that contains all the robot-specific data.  Configuring for our robot is now simply a matter of entering the correct values.

Let me know your thoughts.

### CODE REVIEW

**Comment by EWall25** [comment]
These all look amazing! Thank you very much for your work on swervepy. I'll try to merge this PR later today.

One thing: there should be separate current limit constants for propulsion and steering motors, as most teams are going to want different values. Thanks!

**Comment by otherjon** [comment]
Separate current limits sound like a good idea to me.  The latest commit should take care of that.  It also fixes a couple of places where I still had my NEOs as the default instead of your Falcon 500s -- either one would be fine, but mixing the two would just cause confusion.

I haven't tested this code on my robot yet (still working on my robot's mechanical problems), but auto-generated software tests are reporting some issues.  They seem to be related to the pathplannerlib transition.  I may not have understood your instructions correctly -- is it now safe to simply `pip install --pre robotpy-pathplannerlib` without doing any additional modifications, and have things work?

**Comment by EWall25** [comment]
Doing `pip install robotpy-pathplannerlib~=2024.0.0b6` should work.

**Comment by EWall25** [comment]
Setting up the environment with the Poetry dependency manager would also automatically install the correct versions, but that should be a job for another day if you're still working on mechanical issues.

**Comment by otherjon** [comment]
FYI, I've been investigating test failures, which I think I can trace to the pathplanner changes.  (This may be why pathplanner isn't officially released yet.)

I've pushed a new branch to my fork, called `undo-pathplanner` -- not that I think you should undo pathplanner, but in order to confirm that I haven't introduced new bugs.  The `undo-pathplanner` branch contains 4 commits on top of the `refactor-example-robot` branch: one adds the default tests (output of `robot.py add-tests`), two are the result of `git revert` on the two pathplanner commits, and the last changes the Falcon 500s to NEOs.  (It looks like the current phoenix5 library doesn't yet work in simulation under 2024 robotpy...)  After reverting the pathplanner changes, the code passes these basic tests.  Without reverting the pathplanner changes, 3 of the 4 tests fail, complaining that the motors were already instantiated (which doesn't seem relevant to the robot code, which only instantiates them once -- confirmed with debug statements).

So: (1) I think that in the long run, adding the default tests to example_robot would be a good idea; (2) I've confirmed that the code I submitted in the `refactor-example-robot` passes default tests except for the pathplannerlib issue; (3) I wanted to make sure you were aware of the fact that the current pathplannerlib interferes with running tests for NEOs (and the current phoenix5 lib doesn't work for running tests at all, as far as I can tell).

**Comment by EWall25** [comment]
Thank you for the update! I will merge as soon as I'm back at my PC today. Once again, I am incredibly grateful for the time you are dedicating to this.

Before I merge, would it be possible for you to revert your last commit (fix param names)? I don't think it fits stylistically with the rest of the parameters. For example, the parameter "ramp_rate" is present for both drive and azimuth components, but it is not separately named "drive_ramp_rate" and "azimuth_ramp_rate." I'd appreciate your feedback on this issue. Thanks.

**Comment by otherjon** [comment]
I'm traveling until the 31st, but I might have GitHub access and some time.  I'll do my best to get to it soon.

**Comment by EWall25** [comment]
Merged! Have safe travels!

**Pull request merged**
